import {
  Column,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from "typeorm";

import { Tablet } from "./tablet.entity";

/**
 * Nonces generated by tablets. Populated by the tablet's periodic nonce sync
 * and lazily by QR verification. `nonce` is globally unique — marking it used
 * relies on this constraint to stay race-safe (replay protection).
 */
@Entity("qr_nonces")
@Index(["tabletId", "issuedTs"])
export class QrNonce {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column("uuid")
  tabletId: string;

  @ManyToOne(() => Tablet, { onDelete: "CASCADE" })
  @JoinColumn({ name: "tabletId" })
  tablet: Tablet;

  /** base64url, 16 bytes. */
  @Index({ unique: true })
  @Column()
  nonce: string;

  /** Unix epoch seconds the tablet generated the nonce at. */
  @Column({ type: "bigint" })
  issuedTs: string;

  @Column({ type: "timestamptz", nullable: true })
  usedAt: Date | null;

  @Column({ type: "uuid", nullable: true })
  usedByUserId: string | null;
}
